import { FastifyRequest, FastifyReply } from 'fastify';
import { APIResponse, HttpStatus } from '@cycletime/shared-types';
import {
  CodeValidationRequest,
  StandardsConfigurationRequest,
  CodeAnalysisRequest,
  Language,
  StandardsCategory,
  EnforcementLevelRequest
} from '../types/standards-types.js';
import { StandardsAnalysisService } from '../services/standards-analysis-service.js';
import { StandardsConfigurationService } from '../services/standards-configuration-service.js';
import { EventService } from '../services/event-service.js';

/**
 * Standards Controller
 * Handles all standards-related API endpoints
 */
export class StandardsController {
  private analysisService: StandardsAnalysisService;
  private configurationService: StandardsConfigurationService;
  private eventService: EventService;

  constructor() {
    this.analysisService = new StandardsAnalysisService();
    this.configurationService = new StandardsConfigurationService();
    this.eventService = new EventService();
  }

  /**
   * POST /api/v1/standards/validate
   * Validate code against team standards
   */
  async validateCode(
    request: FastifyRequest<{ Body: CodeValidationRequest }>,
    reply: FastifyReply
  ): Promise<void> {
    try {
      const validationRequest = request.body;

      // Validate request
      if (!validationRequest.code || !validationRequest.language || !validationRequest.teamId) {
        const response: APIResponse = {
          success: false,
          error: {
            code: 'VALIDATION_ERROR',
            message: 'Missing required fields: code, language, and teamId are required'
          },
          metadata: {
            requestId: request.id,
            timestamp: new Date().toISOString(),
            version: '1.0.0'
          }
        };
        reply.status(HttpStatus.BAD_REQUEST).send(response);
        return;
      }

      // Validate language
      if (!Object.values(Language).includes(validationRequest.language as Language)) {
        const response: APIResponse = {
          success: false,
          error: {
            code: 'INVALID_LANGUAGE',
            message: `Unsupported language: ${validationRequest.language}`
          },
          metadata: {
            requestId: request.id,
            timestamp: new Date().toISOString(),
            version: '1.0.0'
          }
        };
        reply.status(HttpStatus.BAD_REQUEST).send(response);
        return;
      }

      // Perform validation
      const result = await this.analysisService.analyzeCode(validationRequest);

      // Publish analysis event
      await this.eventService.publishStandardsAnalyzed({
        eventId: '', // Will be generated by event service
        timestamp: new Date().toISOString(),
        source: 'standards-engine',
        data: {
          analysisId: `analysis_${Date.now()}`,
          teamId: validationRequest.teamId,
          projectId: validationRequest.projectId || 'unknown',
          files: [
            {
              path: validationRequest.contextPath || 'inline-code',
              language: validationRequest.language,
              score: result.overallScore,
              violationsCount: result.violations.length
            }
          ],
          overallScore: result.overallScore,
          totalViolations: result.violations.length,
          analysisDurationMs: result.analysisTime,
          triggeredBy: 'api_validation'
        }
      });

      const response: APIResponse = {
        success: true,
        data: result,
        metadata: {
          requestId: request.id,
          timestamp: new Date().toISOString(),
          version: '1.0.0',
          processingTime: result.analysisTime
        }
      };

      reply.status(HttpStatus.OK).send(response);
    } catch (error) {
      request.log.error(error, 'Error validating code');
      
      const response: APIResponse = {
        success: false,
        error: {
          code: 'INTERNAL_ERROR',
          message: 'An error occurred while validating code'
        },
        metadata: {
          requestId: request.id,
          timestamp: new Date().toISOString(),
          version: '1.0.0'
        }
      };
      
      reply.status(HttpStatus.INTERNAL_SERVER_ERROR).send(response);
    }
  }

  /**
   * GET /api/v1/standards/team/:teamId/rules
   * Get team-specific standards rules
   */
  async getTeamStandards(
    request: FastifyRequest<{ 
      Params: { teamId: string }; 
      Querystring: { category?: StandardsCategory; active_only?: boolean } 
    }>,
    reply: FastifyReply
  ): Promise<void> {
    try {
      const { teamId } = request.params;
      const { category, active_only } = request.query;

      // Validate UUID format
      if (!this.isValidUUID(teamId)) {
        const response: APIResponse = {
          success: false,
          error: {
            code: 'INVALID_TEAM_ID',
            message: 'Invalid team ID format'
          },
          metadata: {
            requestId: request.id,
            timestamp: new Date().toISOString(),
            version: '1.0.0'
          }
        };
        reply.status(HttpStatus.BAD_REQUEST).send(response);
        return;
      }

      // Get team standards
      const teamStandards = await this.configurationService.getTeamStandards(teamId, category);

      // Filter by active status if requested
      if (active_only) {
        teamStandards.standards = teamStandards.standards.filter(std => std.active);
        teamStandards.totalRules = teamStandards.standards.reduce(
          (total, std) => total + std.rules.length,
          0
        );
      }

      const response: APIResponse = {
        success: true,
        data: teamStandards,
        metadata: {
          requestId: request.id,
          timestamp: new Date().toISOString(),
          version: '1.0.0'
        }
      };

      reply.status(HttpStatus.OK).send(response);
    } catch (error) {
      request.log.error(error, 'Error getting team standards');
      
      const response: APIResponse = {
        success: false,
        error: {
          code: 'INTERNAL_ERROR',
          message: 'An error occurred while retrieving team standards'
        },
        metadata: {
          requestId: request.id,
          timestamp: new Date().toISOString(),
          version: '1.0.0'
        }
      };
      
      reply.status(HttpStatus.INTERNAL_SERVER_ERROR).send(response);
    }
  }

  /**
   * POST /api/v1/standards/configure
   * Configure team standards
   */
  async configureStandards(
    request: FastifyRequest<{ Body: StandardsConfigurationRequest }>,
    reply: FastifyReply
  ): Promise<void> {
    try {
      const configurationRequest = request.body;

      // Validate configuration
      const validation = await this.configurationService.validateConfiguration(configurationRequest);
      
      if (!validation.valid) {
        const response: APIResponse = {
          success: false,
          error: {
            code: 'CONFIGURATION_INVALID',
            message: 'Invalid configuration',
            details: {
              errors: validation.errors,
              warnings: validation.warnings
            }
          },
          metadata: {
            requestId: request.id,
            timestamp: new Date().toISOString(),
            version: '1.0.0'
          }
        };
        reply.status(HttpStatus.BAD_REQUEST).send(response);
        return;
      }

      // Configure standards
      const result = await this.configurationService.configureStandards(configurationRequest);

      // Count total rules and standards
      const rulesCount = configurationRequest.standards.reduce(
        (total, std) => total + std.rules.length,
        0
      );

      const response: APIResponse = {
        success: true,
        data: {
          teamId: configurationRequest.teamId,
          standardsCount: configurationRequest.standards.length,
          rulesCount,
          configurationId: result.configurationId
        },
        metadata: {
          requestId: request.id,
          timestamp: new Date().toISOString(),
          version: '1.0.0'
        }
      };

      reply.status(HttpStatus.OK).send(response);
    } catch (error) {
      request.log.error(error, 'Error configuring standards');
      
      const response: APIResponse = {
        success: false,
        error: {
          code: 'INTERNAL_ERROR',
          message: 'An error occurred while configuring standards'
        },
        metadata: {
          requestId: request.id,
          timestamp: new Date().toISOString(),
          version: '1.0.0'
        }
      };
      
      reply.status(HttpStatus.INTERNAL_SERVER_ERROR).send(response);
    }
  }

  /**
   * GET /api/v1/standards/templates
   * Get standards templates
   */
  async getStandardsTemplates(
    request: FastifyRequest<{ 
      Querystring: { language?: Language; framework?: string } 
    }>,
    reply: FastifyReply
  ): Promise<void> {
    try {
      const { language, framework } = request.query;

      // Validate language if provided
      if (language && !Object.values(Language).includes(language)) {
        const response: APIResponse = {
          success: false,
          error: {
            code: 'INVALID_LANGUAGE',
            message: `Unsupported language: ${language}`
          },
          metadata: {
            requestId: request.id,
            timestamp: new Date().toISOString(),
            version: '1.0.0'
          }
        };
        reply.status(HttpStatus.BAD_REQUEST).send(response);
        return;
      }

      // Get templates
      const templates = await this.configurationService.getTemplates(language, framework);

      const response: APIResponse = {
        success: true,
        data: {
          templates,
          totalCount: templates.length
        },
        metadata: {
          requestId: request.id,
          timestamp: new Date().toISOString(),
          version: '1.0.0'
        }
      };

      reply.status(HttpStatus.OK).send(response);
    } catch (error) {
      request.log.error(error, 'Error getting templates');
      
      const response: APIResponse = {
        success: false,
        error: {
          code: 'INTERNAL_ERROR',
          message: 'An error occurred while retrieving templates'
        },
        metadata: {
          requestId: request.id,
          timestamp: new Date().toISOString(),
          version: '1.0.0'
        }
      };
      
      reply.status(HttpStatus.INTERNAL_SERVER_ERROR).send(response);
    }
  }

  /**
   * POST /api/v1/standards/analyze/code
   * Analyze code compliance with AI insights
   */
  async analyzeCodeCompliance(
    request: FastifyRequest<{ Body: CodeAnalysisRequest }>,
    reply: FastifyReply
  ): Promise<void> {
    try {
      const analysisRequest = request.body;

      // Validate request
      if (!analysisRequest.files || analysisRequest.files.length === 0) {
        const response: APIResponse = {
          success: false,
          error: {
            code: 'VALIDATION_ERROR',
            message: 'At least one file is required for analysis'
          },
          metadata: {
            requestId: request.id,
            timestamp: new Date().toISOString(),
            version: '1.0.0'
          }
        };
        reply.status(HttpStatus.BAD_REQUEST).send(response);
        return;
      }

      if (!analysisRequest.teamId) {
        const response: APIResponse = {
          success: false,
          error: {
            code: 'VALIDATION_ERROR',
            message: 'Team ID is required'
          },
          metadata: {
            requestId: request.id,
            timestamp: new Date().toISOString(),
            version: '1.0.0'
          }
        };
        reply.status(HttpStatus.BAD_REQUEST).send(response);
        return;
      }

      // Validate file languages
      for (const file of analysisRequest.files) {
        if (!Object.values(Language).includes(file.language as Language)) {
          const response: APIResponse = {
            success: false,
            error: {
              code: 'INVALID_LANGUAGE',
              message: `Unsupported language in file ${file.path}: ${file.language}`
            },
            metadata: {
              requestId: request.id,
              timestamp: new Date().toISOString(),
              version: '1.0.0'
            }
          };
          reply.status(HttpStatus.BAD_REQUEST).send(response);
          return;
        }
      }

      // Perform analysis
      const result = await this.analysisService.analyzeFiles(analysisRequest);

      // Publish analysis event
      await this.eventService.publishStandardsAnalyzed({
        eventId: '', // Will be generated by event service
        timestamp: new Date().toISOString(),
        source: 'standards-engine',
        data: {
          analysisId: result.analysisId,
          teamId: analysisRequest.teamId,
          projectId: analysisRequest.projectId || 'unknown',
          files: result.fileAnalyses.map(fa => ({
            path: fa.filePath,
            language: fa.language,
            score: fa.score,
            violationsCount: fa.violations.length
          })),
          overallScore: result.overallScore,
          totalViolations: result.fileAnalyses.reduce((total, fa) => total + fa.violations.length, 0),
          analysisDurationMs: result.processingTime,
          triggeredBy: 'api_analysis'
        }
      });

      const response: APIResponse = {
        success: true,
        data: result,
        metadata: {
          requestId: request.id,
          timestamp: new Date().toISOString(),
          version: '1.0.0',
          processingTime: result.processingTime
        }
      };

      reply.status(HttpStatus.OK).send(response);
    } catch (error) {
      request.log.error(error, 'Error analyzing code compliance');
      
      const response: APIResponse = {
        success: false,
        error: {
          code: 'INTERNAL_ERROR',
          message: 'An error occurred while analyzing code compliance'
        },
        metadata: {
          requestId: request.id,
          timestamp: new Date().toISOString(),
          version: '1.0.0'
        }
      };
      
      reply.status(HttpStatus.INTERNAL_SERVER_ERROR).send(response);
    }
  }

  /**
   * DELETE /api/v1/standards/rule/:ruleId
   * Delete a specific standards rule
   */
  async deleteStandardsRule(
    request: FastifyRequest<{ 
      Params: { ruleId: string };
      Querystring: { teamId: string }
    }>,
    reply: FastifyReply
  ): Promise<void> {
    try {
      const { ruleId } = request.params;
      const { teamId } = request.query;

      // Validate required parameters
      if (!ruleId || !teamId) {
        const response: APIResponse = {
          success: false,
          error: {
            code: 'VALIDATION_ERROR',
            message: 'Both ruleId and teamId are required'
          },
          metadata: {
            requestId: request.id,
            timestamp: new Date().toISOString(),
            version: '1.0.0'
          }
        };
        reply.status(HttpStatus.BAD_REQUEST).send(response);
        return;
      }

      // Validate UUID format for team ID
      if (!this.isValidUUID(teamId)) {
        const response: APIResponse = {
          success: false,
          error: {
            code: 'INVALID_TEAM_ID',
            message: 'Invalid team ID format'
          },
          metadata: {
            requestId: request.id,
            timestamp: new Date().toISOString(),
            version: '1.0.0'
          }
        };
        reply.status(HttpStatus.BAD_REQUEST).send(response);
        return;
      }

      // Delete the rule
      await this.configurationService.deleteRule(ruleId, teamId);

      const response: APIResponse = {
        success: true,
        data: {
          ruleId,
          teamId,
          deletedAt: new Date().toISOString()
        },
        metadata: {
          requestId: request.id,
          timestamp: new Date().toISOString(),
          version: '1.0.0'
        }
      };

      reply.status(HttpStatus.OK).send(response);
    } catch (error) {
      request.log.error(error, 'Error deleting rule');

      if (error instanceof Error && error.message.includes('not found')) {
        const response: APIResponse = {
          success: false,
          error: {
            code: 'NOT_FOUND',
            message: error.message
          },
          metadata: {
            requestId: request.id,
            timestamp: new Date().toISOString(),
            version: '1.0.0'
          }
        };
        reply.status(HttpStatus.NOT_FOUND).send(response);
        return;
      }
      
      const response: APIResponse = {
        success: false,
        error: {
          code: 'INTERNAL_ERROR',
          message: 'An error occurred while deleting the rule'
        },
        metadata: {
          requestId: request.id,
          timestamp: new Date().toISOString(),
          version: '1.0.0'
        }
      };
      
      reply.status(HttpStatus.INTERNAL_SERVER_ERROR).send(response);
    }
  }

  /**
   * PUT /api/v1/standards/enforcement/level
   * Set enforcement level for team
   */
  async setEnforcementLevel(
    request: FastifyRequest<{ Body: EnforcementLevelRequest }>,
    reply: FastifyReply
  ): Promise<void> {
    try {
      const enforcementRequest = request.body;

      // Validate request
      if (!enforcementRequest.teamId || !enforcementRequest.level) {
        const response: APIResponse = {
          success: false,
          error: {
            code: 'VALIDATION_ERROR',
            message: 'teamId and level are required'
          },
          metadata: {
            requestId: request.id,
            timestamp: new Date().toISOString(),
            version: '1.0.0'
          }
        };
        reply.status(HttpStatus.BAD_REQUEST).send(response);
        return;
      }

      // Validate UUID format for team ID
      if (!this.isValidUUID(enforcementRequest.teamId)) {
        const response: APIResponse = {
          success: false,
          error: {
            code: 'INVALID_TEAM_ID',
            message: 'Invalid team ID format'
          },
          metadata: {
            requestId: request.id,
            timestamp: new Date().toISOString(),
            version: '1.0.0'
          }
        };
        reply.status(HttpStatus.BAD_REQUEST).send(response);
        return;
      }

      // Set enforcement level
      await this.configurationService.setEnforcementLevel(enforcementRequest);

      // Get updated team standards for response
      const teamStandards = await this.configurationService.getTeamStandards(enforcementRequest.teamId);

      const response: APIResponse = {
        success: true,
        data: {
          teamId: enforcementRequest.teamId,
          level: enforcementRequest.level,
          rulesCount: teamStandards.totalRules,
          updatedAt: new Date().toISOString()
        },
        metadata: {
          requestId: request.id,
          timestamp: new Date().toISOString(),
          version: '1.0.0'
        }
      };

      reply.status(HttpStatus.OK).send(response);
    } catch (error) {
      request.log.error(error, 'Error setting enforcement level');
      
      const response: APIResponse = {
        success: false,
        error: {
          code: 'INTERNAL_ERROR',
          message: 'An error occurred while setting enforcement level'
        },
        metadata: {
          requestId: request.id,
          timestamp: new Date().toISOString(),
          version: '1.0.0'
        }
      };
      
      reply.status(HttpStatus.INTERNAL_SERVER_ERROR).send(response);
    }
  }

  /**
   * Validate UUID format
   */
  private isValidUUID(uuid: string): boolean {
    const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
    return uuidRegex.test(uuid);
  }
}